apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gokulkrishnapprem/2023mcs310003:01
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi

        
